---
kind: LVMCluster
apiVersion: lvm.topolvm.io/v1alpha1
metadata:
  name: lvm-cluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - name: vg1
        default: true
        fstype: xfs
        deviceSelector:
          paths:
            - /dev/disk/by-id/scsi-SDELL_PERC_H330_Adp_00f16c9522af51922f0086f557f098cd
        thinPoolConfig:
          name: thin-pool-1
          chunkSizeCalculationPolicy: Static
          metadataSizeCalculationPolicy: Host
          overprovisionRatio: 10
          sizePercent: 90
