apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: noobaa-default-backing-store
  namespace: openshift-storage
  labels:
    app: noobaa
spec:
  pvPool:
    numVolumes: 1
    resources:
      requests:
        storage: 512Gi
    storageClass: lvms-vg1
  type: pv-pool
