apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  ASSISTED_SERVICE_HOST: 127.0.0.1:8090
  ASSISTED_SERVICE_SCHEME: http
  AUTH_TYPE: none
  DB_HOST: 127.0.0.1
  DB_NAME: installer
  DB_PASS: admin
  DB_PORT: "5432"
  DB_USER: admin
  DEPLOY_TARGET: onprem
  DISK_ENCRYPTION_SUPPORT: "false"
  DUMMY_IGNITION: "false"
  ENABLE_SINGLE_NODE_DNSMASQ: "false"
  HW_VALIDATOR_REQUIREMENTS: '[{"version":"default","master":{"cpu_cores":4,"ram_mib":16384,"disk_size_gb":100,"installation_disk_speed_threshold_ms":10,"network_latency_threshold_ms":100,"packet_loss_percentage":0},"worker":{"cpu_cores":2,"ram_mib":8192,"disk_size_gb":100,"installation_disk_speed_threshold_ms":10,"network_latency_threshold_ms":1000,"packet_loss_percentage":10},"sno":{"cpu_cores":8,"ram_mib":16384,"disk_size_gb":100,"installation_disk_speed_threshold_ms":10},"edge-worker":{"cpu_cores":2,"ram_mib":8192,"disk_size_gb":15,"installation_disk_speed_threshold_ms":10}}]'
  IMAGE_SERVICE_BASE_URL: http://127.0.0.1:8888
  IPV6_SUPPORT: "true"
  ISO_IMAGE_TYPE: "full-iso"
  LISTEN_PORT: "8888"
  NTP_DEFAULT_SERVER: "172.17.10.3"
  POSTGRESQL_DATABASE: installer
  POSTGRESQL_PASSWORD: admin
  POSTGRESQL_USER: admin
  PUBLIC_CONTAINER_REGISTRIES: "quay.io,registry.ci.openshift.org"
  SERVICE_BASE_URL: http://192.168.100.67:8090
  STORAGE: filesystem
  OS_IMAGES: |
    [
        {
            "openshift_version": "4.18",
            "cpu_architecture": "x86_64",
            "url": "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.18/4.18.1/rhcos-4.18.1-x86_64-live.x86_64.iso",
            "version": "418.94.202501221327-0"
        }
    ]
  RELEASE_IMAGES: |
    [
      {
        "openshift_version": "4.18",
        "cpu_architecture": "x86_64",
        "cpu_architectures": ["x86_64"],
        "url": "quay.io/okd/scos-release:4.18.0-okd-scos.8",
        "version": "4.18.0-okd-scos.8",
        "default": true,
        "support_level": "production"
      }
    ]
  ENABLE_UPGRADE_AGENT: "true"
  ENABLE_OKD_SUPPORT: "true"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: assisted-installer
  name: assisted-installer
spec:
  containers:
    - args:
        - run-postgresql
      image: quay.io/sclorg/postgresql-15-c9s:latest
      name: db
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 100Mi
          cpu: 100m
      envFrom:
        - configMapRef:
            name: config
    - image: quay.io/edge-infrastructure/assisted-installer-ui:latest
      name: ui
      ports:
        - hostPort: 8080
          containerPort: 8080
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 100Mi
          cpu: 100m
      envFrom:
        - configMapRef:
            name: config
    - image: quay.io/edge-infrastructure/assisted-image-service:latest
      name: image-service
      ports:
        - hostPort: 8888
          containerPort: 8888
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 100Mi
          cpu: 100m
      envFrom:
        - configMapRef:
            name: config
    - image: quay.io/edge-infrastructure/assisted-service:latest
      name: service
      ports:
        - hostPort: 8090
          containerPort: 8090
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 100Mi
          cpu: 100m
      envFrom:
        - configMapRef:
            name: config
  restartPolicy: Never
