---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: oci-registry
  namespace: default
spec:
  bucketName: oci-registry
  generateBucketName: oci-registry
  storageClassName: openshift-storage.noobaa.io
