---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: cert-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-infra-auth
  namespace: cert-manager
spec:
  method: kubernetes
  mount: okd_admin
  vaultAuthGlobalRef:
    name: vault-infra-global-auth
    namespace: openshift-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-vault-auth-tokenreview-binding
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: cert-manager
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  vaultAuthRef: vault-infra-auth
  type: kv-v2
  mount: admins
  path: sno_api_token_cloudflare
  destination:
    overwrite: true
    create: true
    name: cloudflare-api-token-secret
