apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: acme-account-private-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: api-token
              name: cloudflare-api-token-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-okd-lab-soubilabs-xyz-certificate
  namespace: openshift-ingress
spec:
  commonName: apps.okd.lab.soubilabs.xyz
  dnsNames:
    - "apps.okd.lab.soubilabs.xyz"
    - "*.apps.okd.lab.soubilabs.xyz"
  secretName: apps-okd-lab-soubilabs-xyz-tls
  isCA: false
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-okd-lab-soubilabs-xyz-certificate
  namespace: openshift-config
spec:
  commonName: api.okd.lab.soubilabs.xyz
  dnsNames:
    - "api.okd.lab.soubilabs.xyz"
  secretName: api-okd-lab-soubilabs-xyz-tls
  isCA: false
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
