---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: openshift-gitops
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  namespace: openshift-gitops
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-vault-auth-tokenreview-binding
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: openshift-gitops
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-infra-auth
  namespace: openshift-gitops
spec:
  method: kubernetes
  mount: okd_admin
  vaultAuthGlobalRef:
    name: vault-infra-global-auth
    namespace: openshift-config
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-secret
  namespace: openshift-gitops
spec:
  vaultAuthRef: vault-infra-auth
  type: kv-v2
  mount: admins
  path: argocd_oidc_client_secret_zitadel
  destination:
    overwrite: false
    create: false
    name: argocd-secret
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  controller:
    resources:
      limits:
        memory: 2048Mi
      requests:
        cpu: 250m
        memory: 2048Mi
  ha:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
    enabled: false
  redis:
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 512Mi
  repo:
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 1024Mi
  server:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 256Mi
    route:
      enabled: true
    host: argocd.apps.okd.lab.soubilabs.xyz
  sso: {}
  oidcConfig: |
    name: zitadel
    issuer: https://iam.lab.soubilabs.xyz
    clientID: "315295493125137421"
    clientSecret: $clientSecret
    requestedScopes: ["openid", "profile", "email", "roles"]
  rbac:
    defaultPolicy: ""
    policy: |
      g, infra-admins, role:admin
    scopes: "[roles]"
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
