apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  controller:
    resources:
      limits:
        memory: 2048Mi
      requests:
        cpu: 250m
        memory: 2048Mi
  ha:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
    enabled: false
  rbac:
    defaultPolicy: ""
    policy: |
      g, infra-admins, role:admin
    scopes: "[groups]"
  redis:
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 512Mi
  repo:
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 1024Mi
  server:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 256Mi
    route:
      enabled: true
  sso:
    dex:
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
      openShiftOAuth: true
    provider: dex
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
