apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oidc-client-secret-zitadel
  namespace: openshift-config
spec:
  vaultAuthRef: vault-infra-auth
  type: kv-v2
  mount: admins
  path: sno_oidc_client_secret_zitadel
  destination:
    overwrite: true
    create: true
    name: oidc-client-secret-zitadel
---
# apiVersion: secrets.hashicorp.com/v1beta1
# kind: VaultStaticSecret
# metadata:
#   name: oidc-client-secret-github
#   namespace: openshift-config
# spec:
#   vaultAuthRef: vault-infra-auth
#   type: kv-v2
#   mount: admins
#   path: sno_oidc_client_secret_github
#   destination:
#     overwrite: true
#     create: true
#     name: oidc-client-secret-github
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: zitadel
      mappingMethod: claim
      type: OpenID
      openID:
        clientID: "311817908940530701"
        clientSecret:
          name: oidc-client-secret-zitadel
        extraScopes:
          - email
          - profile
          - urn:zitadel:iam:user:metadata
        extraAuthorizeParameters:
          include_granted_scopes: "true"
        claims:
          preferredUsername:
            - preferred_username
            - email
          name:
            - nickname
            - given_name
            - name
          email:
            - custom_email_claim
            - email
          groups:
            - roles
        issuer: https://iam.lab.soubilabs.xyz
    # - name: github
    #   mappingMethod: claim
    #   type: GitHub
    #   github:
    #     clientID: "Ov23livdeooKIJiI1nXN"
    #     clientSecret:
    #       name: oidc-client-secret-github
    #     organizations:
    #       - SoubiLabs
    #     teams:
    #       - SoubiLabs/infra-admins
