apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: openshift-config
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  namespace: openshift-config
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: openshift-config
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-secret-operator
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-infra-conn
  namespace: vault-secret-operator
spec:
  address: https://secret.lab.soubilabs.xyz
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-infra-auth
  namespace: vault-secret-operator
spec:
  vaultConnectionRef: vault-infra-conn
  method: kubernetes
  mount: okd_admin
  allowedNamespaces: ["*"]
  kubernetes:
    role: vault-auth
    serviceAccount: openshift-config/vault-auth
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-infra-auth
  namespace: openshift-config
spec:
  vaultConnectionRef: vault-secret-operator/vault-infra-conn
  method: kubernetes
  mount: okd_admin
  kubernetes:
    role: vault-auth
    serviceAccount: vault-auth
    audiences:
      - vault
---

