apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: openshift-workflows
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  namespace: openshift-workflows
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-vault-auth-tokenreview-binding
  namespace: openshift-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: openshift-workflows
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-infra-auth
  namespace: openshift-workflows
spec:
  method: kubernetes
  mount: okd_admin
  vaultAuthGlobalRef:
    name: vault-infra-global-auth
    namespace: openshift-config
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argowf-oidc-secret
  namespace: openshift-workflows
spec:
  vaultAuthRef: vault-infra-auth
  type: kv-v2
  mount: admins
  path: argowf_oidc_client_secret_zitadel
  destination:
    overwrite: true
    create: true
    name: argowf-oidc-secret
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-pull-secret
  namespace: openshift-workflows
spec:
  vaultAuthRef: vault-infra-auth
  type: kv-v2
  mount: admins
  path: harbor_bot_infra_pull_secret
  destination:
    overwrite: true
    create: true
    name: harbor-pull-secret
    type: kubernetes.io/dockerconfigjson
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argowf-s3-secret
  namespace: openshift-workflows
spec:
  vaultAuthRef: vault-infra-auth
  type: kv-v2
  mount: admins
  path: argowf_artifacts_s3_credentials
  destination:
    overwrite: false
    create: true
    name: argowf-s3-secret
