apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pull-secret
  namespace: openshift-config
spec:
  vaultAuthRef: vault-infra-auth
  type: kv-v2
  mount: admins
  path: openshift_pull_secret_sno
  destination:
    overwrite: true
    create: true
    name: pull-secret
    type: kubernetes.io/dockerconfigjson
---
apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  annotations:
    capability.openshift.io/name: marketplace
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  disableAllDefaultSources: false
  sources:
    - name: redhat-operators
      disabled: false
    - name: certified-operators
      disabled: false
    - name: community-operators
      disabled: false
    - name: redhat-marketplace
      disabled: false
