sonarr:
  sonarr-default:
    base_url: http://192.168.100.11:8989
    api_key: 502ff5b472be43779406ab45e8b052c0
    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p-fr
      - template: sonarr-v4-custom-formats-web-1080p-multi-fr
      - template: sonarr-v4-custom-formats-web-1080p-fr
      - template: sonarr-quality-definition-anime
      - template: sonarr-v4-quality-profile-anime-fr
      - template: sonarr-v4-custom-formats-anime-fr
    # https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    quality_profiles:
      - name: FR-MULTi-ANIME
        reset_unmatched_scores:
          enabled: true
        qualities:
          - name: Bluray-1080p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: HDTV-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
          - name: HDTV-720p
          - name: Bluray-480p
          - name: WEB 480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p
          - name: DVD
          - name: SDTV
    # https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        quality_profiles:
          - name: FR-MULTi-ANIME
            score: 50 # Ajuster le score comme souhaité

      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
        quality_profiles:
          - name: FR-MULTi-ANIME
            score: 0 # Ajuster le score comme souhaité

      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        quality_profiles:
          - name: FR-MULTi-ANIME
            score: 30 # Ajuster le score comme souhaité
      # - trash_ids:
      #     # Décommenter les sept lignes suivantes pour désactiver les tiers originaux (Anglais)
      #     - e6258996055b9fbab7e9cb2f75819294 # WEB Tier 01
      #     - 58790d4e2fdcd9733aa7ae68ba2bb503 # WEB Tier 02
      #     - d84935abd3f8556dcd51d4f27e22d0a6 # WEB Tier 03
      #     - d0c516558625b04b363fa6c5c2c7cfd4 # WEB Scene
      #   quality_profiles:
      #     - name: FR-MULTi-WEB-1080p
      #       score: 0
      # https://trash-guides.info/Radarr/radarr-setup-quality-profiles-french-en/#french-audio-versions
      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        quality_profiles:
          - name: FR-MULTi-ANIME
            score: 11 # Adjust scoring as desired
      - trash_ids:
          # ===== MULTi Audio =====
          - 72b1548df1ac3175ca105a9ce7043c91 # Multi-Audio
          - d5f3a1afdb77e6b95e489f7654532d04 # Multi-French
        quality_profiles:
          - name: FR-MULTi-ANIME
            score: 21 # Adjust scoring as desired
      - trash_ids:
          - 404c08fd0bd67f39b4d8e5709319094e # VFF
        quality_profiles:
          - name: FR-MULTi-ANIME
            score: 101
      - trash_ids:
          - 52772f1cad6b5d26c2551f79bc538a50 # VFI
        quality_profiles:
          - name: FR-MULTi-ANIME
            score: 51
      - trash_ids:
          - 9172b2f683f6223e3a1846427b417a3d # VOSTFR
        quality_profiles:
          - name: FR-MULTi-ANIME
            score: 11
      - trash_ids:
          - 2c29a39a4fdfd6d258799bc4c09731b9 # VFF
        quality_profiles:
          - name: FR-MULTi-WEB-1080p
            score: 101
      - trash_ids:
          - 7ae924ee9b2f39df3283c6c0beb8a2aa # VOF
        quality_profiles:
          - name: FR-MULTi-WEB-1080p
            # score: 101
      - trash_ids:
          - b6816a0e1d4b64bf3550ad3b74b009b6 # VFI
        quality_profiles:
          - name: FR-MULTi-WEB-1080p
            score: 51
      - trash_ids:
          - 34789ec3caa819f087e23bbf9999daf7 # VF2
        quality_profiles:
          - name: FR-MULTi-WEB-1080p
            # score: 101
      - trash_ids:
          - 7a7f4e4f58bd1058440236d033a90b67 # VFQ
        quality_profiles:
          - name: FR-MULTi-WEB-1080p
            # score: 101
      - trash_ids:
          - 802dd70b856c423a9b0cb7f34ac42be1 # VOQ
        quality_profiles:
          - name: FR-MULTi-WEB-1080p
            # score: 101
      - trash_ids:
          - 82085412d9a53ba8d8e46fc624eb701d # VQ
        quality_profiles:
          - name: FR-MULTi-WEB-1080p
            # score: 101
      - trash_ids:
          - 0ce1e39a4676c6692ce47935278dac76 # VFB
        quality_profiles:
          - name: FR-MULTi-WEB-1080p
            # score: 101
radarr:
  radarr-default:
    base_url: http://192.168.100.11:7878
    api_key: eeb8fee5f4074187840142a923a71dfd
    # https://recyclarr.dev/wiki/yaml/config-reference/#quality-def-settings
    quality_definition:
      type: movie
    include:
      # Comment out any of the following includes to disable them
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime
    # https://recyclarr.dev/wiki/yaml/config-reference/#quality-profiles
    quality_profiles:
      - name: FR HD Bluray + Remux + WEB (MULTi)
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray-1080p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Bluray-1080p
          - name: Remux-1080p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
    # https://recyclarr.dev/wiki/yaml/config-reference/#custom-format-settings
    custom_formats:
      - trash_ids:
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired
      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired
      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 11 # Adjust scoring as desired
      - trash_ids:
          # ===== MULTi Audio =====
          - 72b1548df1ac3175ca105a9ce7043c91 # Multi-Audio
          - d5f3a1afdb77e6b95e489f7654532d04 # Multi-French
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 21 # Adjust scoring as desired
      - trash_ids:
          - 404c08fd0bd67f39b4d8e5709319094e # VFF
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 101
      - trash_ids:
          - 52772f1cad6b5d26c2551f79bc538a50 # VFI
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 51
      - trash_ids:
          - 9172b2f683f6223e3a1846427b417a3d # VOSTFR
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 11
      - trash_ids:
          # ===== MULTi Audio =====
          - 72b1548df1ac3175ca105a9ce7043c91 # Multi-Audio
          - d5f3a1afdb77e6b95e489f7654532d04 # Multi-French
          # ===== Version du film =====
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
          # ===== HQ Release Groups =====
          - 5322da05b19d857acc1e75be3edf47b3 # FR HD Bluray Tier 01
          - 57f34251344be2e283fc30e00e458be6 # FR HD Bluray Tier 02
          - 9790a618cec1aeac8ce75601a17ea40d # FR WEB Tier 01
          - 3c83a765f84239716bd5fd2d7af188f9 # FR WEB Tier 02
          - 0d94489c0d5828cd3bf9409d309fb32b # FR Scene Groups
          # ===== Misc =====
          - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4 # Repack2
          # ===== Indésirables =====
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 48f031e76111f17ea94898f4cdc34fdc # FR LQ
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
          # ===== Services de Streaming =====
          - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
          - 40e9380490e748672c2522eaaeb692f7 # ATVP
          - 16622a6911d1ab5d5b8b713d5b0036d4 # CRiT
          - 84272245b2988854bfb76a16e60baea5 # DSNP
          - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE
          - 509e5f41146e278f9eab1ddaceb34515 # HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
          - 526d445d4c16214309f0fd2b3be18a89 # Hulu
          - 2a6039655313bf5dab1e43523b62c374 # MA
          - 6a061313d22e51e0f25b7cd4dc065233 # MAX
          - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
          - bf7e73dd1d85b12cc527dc619761c840 # Pathe
          - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
          - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
          - c2863d2a50c9acad1fb50e53ece60817 # STAN
        quality_profiles:
          - name: FR HD Bluray + Remux + WEB (MULTi)
      # https://trash-guides.info/Radarr/radarr-setup-quality-profiles-french-en/#french-audio-versions
      - trash_ids:
          - 404c08fd0bd67f39b4d8e5709319094e # VFF
        quality_profiles:
          - name: FR HD Bluray + Remux + WEB (MULTi)
            score: 101
      - trash_ids:
          - 4cafa20d5584f6ba1871d1b8941aa3cb # VOF
        quality_profiles:
          - name: FR HD Bluray + Remux + WEB (MULTi)
            # score: 101
      - trash_ids:
          - 52772f1cad6b5d26c2551f79bc538a50 # VFI
        quality_profiles:
          - name: FR HD Bluray + Remux + WEB (MULTi)
            score: 51
      - trash_ids:
          - 29b5f7b1a5f20f64228786c3ab1bdc7d # VF2
        quality_profiles:
          - name: FR HD Bluray + Remux + WEB (MULTi)
            # score: 101
      - trash_ids:
          - b6ace47331a1d3b77942fc18156f6df6 # VFQ
        quality_profiles:
          - name: FR HD Bluray + Remux + WEB (MULTi)
            # score: 101
      - trash_ids:
          - 95aa50f71a01c82354a7a2b385f1c4d8 # VQ
        quality_profiles:
          - name: FR HD Bluray + Remux + WEB (MULTi)
            # score: 101
      - trash_ids:
          - b3fb499641d7b3c2006be1d9eb014cb3 # VFB
        quality_profiles:
          - name: FR HD Bluray + Remux + WEB (MULTi)
            # score: 101
      - trash_ids:
          - 9172b2f683f6223e3a1846427b417a3d # VOSTFR
        quality_profiles:
          - name: FR HD Bluray + Remux + WEB (MULTi)
