sonarr:
  sonarr-default:
    base_url: http://{{ sonarr_default_ip_port }}
    api_key: "{{ starr_api_key }}"

    include:
      - template: sonarr-quality-definition-series
      # Profile souhaité - veuillez à avoir les lignes correspondantes activées
      # --- Profile VOSTFR ---
      # - template: sonarr-v4-quality-profile-bluray-web-1080p-french-vostfr
      # - template: sonarr-v4-custom-formats-bluray-web-1080p-french-vostfr
      # --- Profile MULTi.VF ---
      - template: sonarr-v4-quality-profile-bluray-web-1080p-french-multi-vf
      - template: sonarr-v4-custom-formats-bluray-web-1080p-french-multi-vf
      # --- Profile MULTi.VO ---
      - template: sonarr-v4-quality-profile-bluray-web-1080p-french-multi-vo
      - template: sonarr-v4-custom-formats-bluray-web-1080p-french-multi-vo

    # Formats Personnalisés (Custom Formats) :
    # https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Optionnels
      # Ils sont optionnels et peuvent ne pas fonctionner correctement avec les profiles FR
      # - trash_ids:
      # - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
      # - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
      # - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
      # - 06d66ab109d4d2eddb2794d21526d140 # Retags
      # - 1b3994c551cbb92a2c781af061f4ab44 # Scene
      # assign_scores_to:
      # - name: FR-VOSTFR-WEB-1080p
      # - name: FR-MULTi-VF-WEB-1080p
      # - name: FR-MULTi-VO-WEB-1080p

      # Décommentez les lignes suivantes pour accepter les releases en x265 HD avec du HDR/DV
      # - trash_ids:
      # - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
      # assign_scores_to:
      # - name: FR-VOSTFR-WEB-1080p
      # score: 0
      # - name: FR-MULTi-VF-WEB-1080p
      # score: 0
      # - name: FR-MULTi-VO-WEB-1080p
      # score: 0
      # - trash_ids:
      # - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
      # assign_scores_to:
      # - name: FR-VOSTFR-WEB-1080p
      # - name: FR-MULTi-VF-WEB-1080p
      # - name: FR-MULTi-VO-WEB-1080p

      # Décommenter le score associé si vous ne voulez pas de FanSUB.
      - trash_ids:
          - 84f0acbda9c0c9de783894fb66df25aa # FanSUB
        assign_scores_to:
          # - name: FR-VOSTFR-WEB-1080p
          # score: -10000
          # - name: FR-MULTi-VF-WEB-1080p
          # score: -10000
          # - name: FR-MULTi-VO-WEB-1080p
          # score: -10000

      # ===== Versions françaises =====
      # Activez ou désactiver les Formats Personnalisés suivant si vous souhaitez noter vos releases
      # avec. Vous pouvez aussi leur attribuer un score en fonction de si vous souhaitez préférer un
      # certain type d'audio français.
      # Par exemple si vous préférez la VFF : VFF + VF2 à 101, VFQ à -101, le reste à 0.
      # Pensez à vérifier aussi à quoi corresponde les différents types de version francophones :
      # https://trash-guides.info/Sadarr/sadarr-setup-quality-profiles-french-fr/#french-audio-versions
      - trash_ids:
          - 2c29a39a4fdfd6d258799bc4c09731b9 # VFF
        assign_scores_to:
          # - name: FR-VOSTFR-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VF-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VO-WEB-1080p
          # score: 101
      - trash_ids:
          - 7ae924ee9b2f39df3283c6c0beb8a2aa # VOF
        assign_scores_to:
          # - name: FR-VOSTFR-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VF-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VO-WEB-1080p
          # score: 101
      - trash_ids:
          - b6816a0e1d4b64bf3550ad3b74b009b6 # VFI
        assign_scores_to:
          # - name: FR-VOSTFR-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VF-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VO-WEB-1080p
          # score: 101
      - trash_ids:
          - 34789ec3caa819f087e23bbf9999daf7 # VF2
        assign_scores_to:
          # - name: FR-VOSTFR-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VF-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VO-WEB-1080p
          # score: 101
      - trash_ids:
          - 7a7f4e4f58bd1058440236d033a90b67 # VFQ
        assign_scores_to:
          # - name: FR-VOSTFR-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VF-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VO-WEB-1080p
          # score: 101
      - trash_ids:
          - 802dd70b856c423a9b0cb7f34ac42be1 # VOQ
        assign_scores_to:
          # - name: FR-VOSTFR-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VF-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VO-WEB-1080p
          # score: 101
      - trash_ids:
          - 82085412d9a53ba8d8e46fc624eb701d # VQ
        assign_scores_to:
          # - name: FR-VOSTFR-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VF-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VO-WEB-1080p
          # score: 101
      - trash_ids:
          - 0ce1e39a4676c6692ce47935278dac76 # VFB
        assign_scores_to:
          # - name: FR-VOSTFR-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VF-WEB-1080p
          # score: 101
          # - name: FR-MULTi-VO-WEB-1080p
          # score: 101
  sonarr-anime:
    base_url: http://{{ sonarr_anime_ip_port }}
    api_key: "{{ starr_api_key }}"

    include:
      - template: sonarr-quality-definition-anime
      # Profile souhaité - veuillez à avoir les lignes correspondantes activées
      # --- Profile VOSTFR ---
      # - template: sonarr-v4-quality-profile-1080p-french-anime-vostfr
      # - template: sonarr-v4-custom-formats-1080p-french-anime-vostfr
      # --- Profile MULTi.VO ---
      - template: sonarr-v4-quality-profile-1080p-french-anime-multi
      - template: sonarr-v4-custom-formats-1080p-french-anime-multi

    # Formats Personnalisés (Custom Formats) :
    # https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Décommenter le score associé si vous préférez les groupes de FanSUB.
      - trash_ids:
          - 44b6c964dad997577d793fd004a39224 # FR Anime FanSub
        assign_scores_to:
          # - name: FR-ANIME-VOSTFR
          # score: 1700
          - name: FR-ANIME-MULTi
            score: 1700

      # Décommenter le score associé si vous ne voulez pas de FanSUB.
      - trash_ids:
          - 84f0acbda9c0c9de783894fb66df25aa # FanSUB
        assign_scores_to:
          # - name: FR-ANIME-VOSTFR
          # score: -10000
          # - name: FR-ANIME-MULTi
          # score: -10000

      # Ajuster le score comme souhaité pour les Formats Personnalisés suivant
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        assign_scores_to:
          # - name: FR-ANIME-VOSTFR
          # score: 0 # Ajuster le score comme souhaité
          # - name: FR-ANIME-MULTi
          # score: 0 # Ajuster le score comme souhaité
      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
        assign_scores_to:
          # - name: FR-ANIME-VOSTFR
          # score: 0 # Ajuster le score comme souhaité
          # - name: FR-ANIME-MULTi
          # score: 0 # Ajuster le score comme souhaité
      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          # - name: FR-ANIME-VOSTFR
          # score: 0 # Ajuster le score comme souhaité
          # - name: FR-ANIME-MULTi
          # score: 0 # Ajuster le score comme souhaité
radarr:
  radarr-default:
    base_url: http://{{ radarr_default_ip_port }}
    api_key: "{{ starr_api_key }}"
    include:
      - template: radarr-quality-definition-movie
      # Profile souhaité - veuillez à avoir les lignes correspondantes activées
      # --- Profile VOSTFR ---
      # - template: radarr-quality-profile-hd-bluray-web-french-vostfr
      # - template: radarr-custom-formats-hd-bluray-web-french-vostfr
      # --- Profile MULTi.VF ---
      - template: radarr-quality-profile-hd-bluray-web-french-multi-vf
      - template: radarr-custom-formats-hd-bluray-web-french-multi-vf
      # --- Profile MULTi.VO ---
      - template: radarr-quality-profile-hd-bluray-web-french-multi-vo
      - template: radarr-custom-formats-hd-bluray-web-french-multi-vo

    # Formats Personnalisés (Custom Formats) :
    # https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Movie Versions
      - trash_ids:
        # Décommentez n'importe laquelle des lignes suivantes pour préférer ces versions de films
        # - 570bc9ebecd92723d2d21500f4be314c # Remaster
        # - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
        # - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
        # - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
        # - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
        # - 957d0f44b592285f26449575e8b1167e # Special Edition
        # - eecf3a857724171f968a66cb5719e152 # IMAX
        # - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          # - name: FR-VOSTFR-HD
          - name: FR-MULTi-VF-HD
          - name: FR-MULTi-VO-HD

      # Optionnels
      # Ils sont optionnels et peuvent ne pas fonctionner correctement avec les profiles FR
      - trash_ids:
          # - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          # - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          # - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          # - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          # - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          # - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          # - name: FR-VOSTFR-HD
          - name: FR-MULTi-VF-HD
          - name: FR-MULTi-VO-HD

      # Décommentez les lignes suivantes pour accepter les releases en x265 HD avec du HDR/DV
      - trash_ids:
          # - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        # assign_scores_to:
        # - name: FR-VOSTFR-HD
        # score: 0
        # - name: FR-MULTi-VF-HD
        # score: 0
        # - name: FR-MULTi-VO-HD
        # score: 0
        # - trash_ids:
        # - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
        assign_scores_to:
          # - name: FR-VOSTFR-HD
          - name: FR-MULTi-VF-HD
          - name: FR-MULTi-VO-HD

      # Décommenter le score associé si vous ne voulez pas de FanSUB.
      - trash_ids:
          - 02e48d30a176c91baf9e15de05e5dc6a # FanSUB
        assign_scores_to:
          # - name: FR-VOSTFR-HD
          # score: -10000
          # - name: FR-MULTi-VF-HD
          # score: -10000
          # - name: FR-MULTi-VO-HD
          # score: -10000

      # ===== Versions françaises =====
      # Activez ou désactiver les Formats Personnalisés suivant si vous souhaitez noter vos releases
      # avec. Vous pouvez aussi leur attribuer un score en fonction de si vous souhaitez préférer un
      # certain type d'audio français.
      # Par exemple si vous préférez la VFF : VFF + VF2 à 101, VFQ à -101, le reste à 0.
      # Pensez à vérifier aussi à quoi corresponde les différents types de version francophones :
      # https://trash-guides.info/Radarr/radarr-setup-quality-profiles-french-en/#french-audio-versions
      - trash_ids:
          - 404c08fd0bd67f39b4d8e5709319094e # VFF
        assign_scores_to:
          # - name: FR-VOSTFR-HD
          # score: 101
          - name: FR-MULTi-VF-HD
          # score: 101
          - name: FR-MULTi-VO-HD
            # score: 101
      - trash_ids:
          - 4cafa20d5584f6ba1871d1b8941aa3cb # VOF
        assign_scores_to:
          # - name: FR-VOSTFR-HD
          # score: 101
          - name: FR-MULTi-VF-HD
          # score: 101
          - name: FR-MULTi-VO-HD
            # score: 101
      - trash_ids:
          - 52772f1cad6b5d26c2551f79bc538a50 # VFI
        assign_scores_to:
          # - name: FR-VOSTFR-HD
          # score: 101
          - name: FR-MULTi-VF-HD
          # score: 101
          - name: FR-MULTi-VO-HD
            # score: 101
      - trash_ids:
          - 29b5f7b1a5f20f64228786c3ab1bdc7d # VF2
        assign_scores_to:
          # - name: FR-VOSTFR-HD
          # score: 101
          - name: FR-MULTi-VF-HD
          # score: 101
          - name: FR-MULTi-VO-HD
            # score: 101
      - trash_ids:
          - b6ace47331a1d3b77942fc18156f6df6 # VFQ
        assign_scores_to:
          # - name: FR-VOSTFR-HD
          # score: 101
          - name: FR-MULTi-VF-HD
          # score: 101
          - name: FR-MULTi-VO-HD
            # score: 101
      - trash_ids:
          - f7caa1942be5cc547c266bd3dbc2cda9 # VOQ
        assign_scores_to:
          # - name: FR-VOSTFR-HD
          # score: 101
          - name: FR-MULTi-VF-HD
          # score: 101
          - name: FR-MULTi-VO-HD
            # score: 101
      - trash_ids:
          - 95aa50f71a01c82354a7a2b385f1c4d8 # VQ
        assign_scores_to:
          # - name: FR-VOSTFR-HD
          # score: 101
          - name: FR-MULTi-VF-HD
          # score: 101
          - name: FR-MULTi-VO-HD
            # score: 101
      - trash_ids:
          - b3fb499641d7b3c2006be1d9eb014cb3 # VFB
        assign_scores_to:
          # - name: FR-VOSTFR-HD
          # score: 101
          - name: FR-MULTi-VF-HD
          # score: 101
          - name: FR-MULTi-VO-HD
            # score: 101
  radarr-anime:
    base_url: http://{{ radarr_anime_ip_port }}
    api_key: "{{ starr_api_key }}"

    include:
      # Comment out any of the following includes to disable them
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime

    # Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      - trash_ids:
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired
