---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: infra-ipp
  labels:
    zone: infra
spec:
  addresses:
    - 192.168.100.96/27
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: paas-ipp
  labels:
    zone: paas
spec:
  addresses:
    - 192.168.110.1/26
  serviceAllocation:
    serviceSelectors:
      - matchLabels:
          zone: paas
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: services-ipp
  labels:
    zone: services
spec:
  addresses:
    - 192.168.120.24/29
  serviceAllocation:
    priority: 50
    serviceSelectors:
      - matchLabels:
          zone: services
