name: Ignition as a service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build coreos/Containerfile
      run: docker build . --file coreos/Containerfile --tag ignition-server:$(date +%s)
