name: Ignition as a service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build coreos/Containerfile
      run: |
        docker build . --file coreos/Containerfile --tag ghcr.io/soubinan/ignition-server:latest \
        --label "org.opencontainers.image.source=https://github.com/soubinan/IaC" \
        --label "org.opencontainers.image.description=Ignition as a service" \
  push:
    needs: build
    if: github.event.created == true && startsWith(github.ref, 'refs/tags/v*.*.*')
    runs-on: ubuntu-latest
    steps:
    - run: |
        docker tag ghcr.io/soubinan/ignition-server:latest ghcr.io/soubinan/ignition-server:${{ github.ref_name }}
        docker login ghcr.io -u soubinan --password ${{ secrets.GHP }}
        docker push ghcr.io/soubinan/ignition-server:latest
        docker push ghcr.io/soubinan/ignition-server:${{ github.ref_name }}
