name: Ignition as a service

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]
  release:
    types: [published]

env:
  TEST_TAG: soubinan/ignition-server:test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/soubinan/ignition-server
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=pr
            type=raw,latest
          labels: |
            --label "org.opencontainers.image.source=https://github.com/soubinan/IaC/coreos"
            --label "org.opencontainers.image.url=https://github.com/soubinan/IaC/coreos"
            --label "org.opencontainers.image.description=Ignition as a service"
            --label "org.opencontainers.image.title=Ignition-Server"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:coreos"
          file: "./Containerfile"
          load: true
          tags: ${{ env.TEST_TAG }}
      # - name: Test
      #   run: |
      #     docker run --rm ${{ env.TEST_TAG }}
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHP }}
        if: github.event_name == 'release'
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:coreos"
          platforms: linux/amd64,linux/arm64
          file: "./Containerfile"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
        if: github.event_name == 'release'
